spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
  liquibase:
    enabled: false

encryption:
  password: super-secret-key

rsa:
  private-key: classpath:certs/private-test.pem
  public-key: classpath:certs/public-test.pem